import { escapeLatex } from './latex.js'

const SECTION_TITLES = {
  pt: {
    resumo: 'Resumo Profissional',
    competencias: 'Competências Técnicas',
    experiencia: 'Experiência Profissional',
    formacao: 'Formação Acadêmica',
    idiomas: 'Idiomas',
  },
  en: {
    resumo: 'Professional Summary',
    competencias: 'Technical Skills',
    experiencia: 'Professional Experience',
    formacao: 'Education',
    idiomas: 'Languages',
  },
}

function pick(field, lang, { required = true, label = 'field' } = {}) {
  if (field == null) {
    if (required) throw new Error(`Missing ${label}`)
    return ''
  }
  if (typeof field === 'string') return field
  if (typeof field === 'object') {
    if (field[lang] != null) return field[lang]
    if (required) throw new Error(`Missing "${lang}" translation for ${label}`)
    return ''
  }
  return String(field)
}

function stripForLatex(value) {
  return value.replace(/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}\u{FE0F}]/gu, '').trim()
}

function buildSkillsRows(stacks, lang) {
  return stacks
    .map((group) => {
      const label = escapeLatex(pick(group.label, lang, { label: 'stacks[].label' }))
      const items = escapeLatex(group.items.join(', '))
      return `${label} & ${items} \\\\`
    })
    .join('\n')
}

function buildExperienceEntries(experiences, lang) {
  return experiences
    .map((job) => {
      const company = escapeLatex(job.company)
      const start = escapeLatex(pick(job.start, lang, { label: 'experiences[].start' }))
      const end = escapeLatex(pick(job.end, lang, { label: 'experiences[].end' }))
      let role = escapeLatex(pick(job.role, lang, { label: 'experiences[].role' }))
      if (job.tag) {
        role += ` -- ${escapeLatex(stripForLatex(job.tag))}`
      }
      const location = escapeLatex(pick(job.location, lang, { label: 'experiences[].location' }))
      const bullets = pick(job.bullets, lang, { label: 'experiences[].bullets' })
      const bulletLines = bullets.map((b) => `\\item ${escapeLatex(b)}`)

      if (job.highlight) {
        const highlight = escapeLatex(pick(job.highlight, lang, { label: 'experiences[].highlight' }))
        bulletLines.push(`\\item \\textbf{${highlight}}`)
      }

      const body = bulletLines.join('\n')
      return `{${company}|${start} - ${end}|${role}|${location}|%\n${body}}`
    })
    .join(',%\n')
}

function buildLanguageRows(languages, lang) {
  return languages
    .map((entry) => {
      const label = escapeLatex(pick(entry.label, lang, { label: 'languages[].label' }))
      const level = escapeLatex(pick(entry.level, lang, { label: 'languages[].level' }))
      return `${label} & ${level} \\\\`
    })
    .join('\n')
}

export function generateCurriculoTex(input, lang) {
  const { contact, experiences, stacks, education } = input
  const titles = SECTION_TITLES[lang] ?? SECTION_TITLES.en
  const edu = education[0]
  if (!edu) throw new Error('education.json needs at least one entry')

  const lines = [
    `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%`,
    `% Generated by dynamic-cv - do not edit by hand.`,
    `% Re-run "npm run build-cv" after changing files in input/.`,
    `% Language: ${lang}`,
    `%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%`,
    '',
    `\\newcommand{\\cvname}{${escapeLatex(contact.name)}}`,
    `\\newcommand{\\cvaddress}{${escapeLatex(pick(contact.location, lang, { label: 'contact.location' }))}}`,
    `\\newcommand{\\cvphone}{${escapeLatex(contact.phone)}}`,
    `\\newcommand{\\cvemail}{${escapeLatex(contact.email)}}`,
    `\\newcommand{\\cvlinkedin}{${escapeLatex(contact.linkedin)}}`,
    '',
    `\\newcommand{\\resumoprofissional}{%`,
    escapeLatex(pick(contact.summary, lang, { label: 'contact.summary' })),
    `}`,
    '',
    `\\newcommand{\\tituloResumo}{${titles.resumo}}`,
    `\\newcommand{\\tituloCompetencias}{${titles.competencias}}`,
    `\\newcommand{\\tituloExperiencia}{${titles.experiencia}}`,
    `\\newcommand{\\tituloFormacao}{${titles.formacao}}`,
    `\\newcommand{\\tituloIdiomas}{${titles.idiomas}}`,
    '',
    `\\newcommand{\\skillsRows}{%`,
    buildSkillsRows(stacks, lang),
    `}`,
    '',
    `\\newcommand{\\experiencias}{%`,
    buildExperienceEntries(experiences, lang),
    `%`,
    `}`,
    '',
    `\\newcommand{\\formacaoInstituicao}{${escapeLatex(pick(edu.institution, lang, { label: 'education[0].institution' }))}}`,
    `\\newcommand{\\formacaoData}{${escapeLatex(pick(edu.start, lang, { label: 'education[0].start' }))} - ${escapeLatex(pick(edu.end, lang, { label: 'education[0].end' }))}}`,
    `\\newcommand{\\formacaoCurso}{${escapeLatex(pick(edu.degree, lang, { label: 'education[0].degree' }))}}`,
    `\\newcommand{\\formacaoDesc}{${escapeLatex(pick(edu.description, lang, { label: 'education[0].description' }))}}`,
    '',
    `\\newcommand{\\idiomaRows}{%`,
    buildLanguageRows(input.languages, lang),
    `}`,
    '',
  ]

  return lines.join('\n')
}
