import type { Content, EducationEntry, ExperienceEntry, LanguageEntry, Locale, SkillGroup } from './types'

// This module builds `Content` (the shape every view component consumes) from
// the JSON generated by the dynamic-cv CLI. Regenerate with (from dynamic-cv/):
//   npm start                       (guided wizard: scan a PDF or fill basics, build, export)
// or run the steps individually:
//   npm run build-cv && npm run export-to-site

import ptContact from './site-content/pt/contact.json'
import ptExperiences from './site-content/pt/experiences.json'
import ptStacks from './site-content/pt/stacks.json'
import ptEducation from './site-content/pt/education.json'
import ptLanguages from './site-content/pt/languages.json'
import ptHomepage from './site-content/pt/homepage.json'
import ptWebsiteOnly from './site-content/pt/websiteonly.json'

import enContact from './site-content/en/contact.json'
import enExperiences from './site-content/en/experiences.json'
import enStacks from './site-content/en/stacks.json'
import enEducation from './site-content/en/education.json'
import enLanguages from './site-content/en/languages.json'
import enHomepage from './site-content/en/homepage.json'
import enWebsiteOnly from './site-content/en/websiteonly.json'

interface SiteContact {
  name: string
  jobTitle: string
  location: string
  email: string
  linkedin: string
  linkedinUrl: string
  github: string
  githubUrl: string
}

interface SiteExperience {
  company: string
  start: string
  end: string
  role: string
  location: string
  bullets: string[]
  tech: string[]
  tag: string | null
  highlight: string | null
}

interface SiteEducation {
  institution: string
  start: string
  end: string
  degree: string
  description: string
}

interface SiteLanguage {
  code: string
  label: string
  level: string
}

interface SiteHomepage {
  meta: { title: string; description: string }
  nav: { home: string; about: string; experience: string; skills: string; education: string; contact: string }
  kicker: string
  welcome: string[]
  tagline: string
  speaks: string
  cta1: string
  cta2: string
  resumeLabel: string
  aboutHeading: string
  aboutParagraphs: string[]
  aboutStats: { value: string; label: string }[]
  experienceHeading: string
  experienceSub: string
  skillsHeading: string
  skillsSub: string
  languagesHeading: string
  contactHeading: string
  contactSub: string
  contactCta: string
}

export interface ProfileCardData {
  avatarUrl: string
  handle: string
  iconUrl: string
}

interface SiteWebsiteOnly {
  profileCard: ProfileCardData
  resumeFiles: string
  footer: string
  companyLogos: Record<string, string>
  companyClouds: Record<string, string[]>
}

interface SiteBundle {
  contact: SiteContact
  experiences: SiteExperience[]
  stacks: SkillGroup[]
  education: SiteEducation[]
  languages: SiteLanguage[]
  homepage: SiteHomepage
  websiteonly: SiteWebsiteOnly
}

function buildContent(bundle: SiteBundle): Content {
  const { contact, experiences, stacks, education, languages, homepage, websiteonly } = bundle

  return {
    meta: homepage.meta,
    nav: homepage.nav,
    hero: {
      kicker: homepage.kicker,
      welcome: homepage.welcome,
      name: contact.name,
      role: contact.jobTitle,
      tagline: homepage.tagline,
      location: contact.location,
      speaks: homepage.speaks,
      cta1: homepage.cta1,
      cta2: homepage.cta2,
      resume: homepage.resumeLabel,
      resumeFile: websiteonly.resumeFiles,
    },
    about: {
      heading: homepage.aboutHeading,
      paragraphs: homepage.aboutParagraphs,
      stats: homepage.aboutStats,
    },
    experience: {
      heading: homepage.experienceHeading,
      sub: homepage.experienceSub,
      items: experiences.map(
        (job): ExperienceEntry => ({
          company: job.company,
          role: job.role,
          start: job.start,
          end: job.end,
          location: job.location,
          bullets: job.bullets,
          tech: job.tech,
          tag: job.tag ?? undefined,
          highlight: job.highlight ?? undefined,
        }),
      ),
    },
    skills: {
      heading: homepage.skillsHeading,
      sub: homepage.skillsSub,
      groups: stacks,
    },
    education: {
      heading: homepage.nav.education,
      items: education.map(
        (edu): EducationEntry => ({
          school: edu.institution,
          degree: edu.degree,
          start: edu.start,
          end: edu.end,
          description: edu.description,
        }),
      ),
      languagesHeading: homepage.languagesHeading,
      languages: languages.map(
        (lang): LanguageEntry => ({
          code: lang.code,
          name: lang.label,
          level: lang.level,
        }),
      ),
    },
    contact: {
      heading: homepage.contactHeading,
      sub: homepage.contactSub,
      cta: homepage.contactCta,
      email: contact.email,
      linkedin: contact.linkedin,
      linkedinUrl: contact.linkedinUrl,
      github: contact.github,
      githubUrl: contact.githubUrl,
    },
    footer: {
      text: websiteonly.footer,
    },
  }
}

const pt = buildContent({
  contact: ptContact,
  experiences: ptExperiences,
  stacks: ptStacks,
  education: ptEducation,
  languages: ptLanguages,
  homepage: ptHomepage as SiteHomepage,
  websiteonly: ptWebsiteOnly,
})

const en = buildContent({
  contact: enContact,
  experiences: enExperiences,
  stacks: enStacks,
  education: enEducation,
  languages: enLanguages,
  homepage: enHomepage as SiteHomepage,
  websiteonly: enWebsiteOnly,
})

export const content: Record<Locale, Content> = { pt, en }

export const profileCard: Record<Locale, ProfileCardData> = {
  pt: ptWebsiteOnly.profileCard,
  en: enWebsiteOnly.profileCard,
}
